name: locale_sheet
description: >
  `locale_sheet` is a lightweight Dart CLI and library that treats an Excel spreadsheet as a single source of truth and converts localization strings into multiple output formats (currently: ARB).
version: 0.0.1
license: MIT
repository: https://github.com/willow-c/locale_sheet
homepage: https://github.com/willow-c/locale_sheet
documentation: https://github.com/willow-c/locale_sheet#readme
issue_tracker: https://github.com/willow-c/locale_sheet/issues
topics:
  - localization
  - cli
  - arb
  - excel
  - i18n
executables:
  locale_sheet:

environment:
  sdk: ">=3.10.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  excel: ^4.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  mocktail: ^1.0.4
